import { useState, useEffect } from 'react';
import { Shield, Smartphone, ArrowRight, CheckCircle2 } from 'lucide-react';
import axios from 'axios';
import { useSelector } from 'react-redux';
import type { RootState } from '../store';

export const MFASettings = () => {
  const [qrCode, setQrCode] = useState('');
  const [secret, setSecret] = useState('');
  const [token, setToken] = useState('');
  const [step, setStep] = useState(1);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  // Since we don't have the global ID exposed easily in Redux, we fallback or fetch it
  const userId = "temp-demo-id"; // For demo purposes until integrated fully

  useEffect(() => {
    const fetchMFA = async () => {
      const API_URL = `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api`;
      try {
        const res = await axios.post(`${API_URL}/auth/enable-2fa`, { userId });
        setQrCode(res.data.qrCode);
        setSecret(res.data.secret);
      } catch (err) {
        console.error("Failed to init MFA", err);
      }
    };
    fetchMFA();
  }, []);

  const handleVerify = async () => {
    setIsLoading(true);
    setError(null);
    const API_URL = `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api`;
    try {
      await axios.post(`${API_URL}/auth/confirm-2fa`, { userId, token });
      setStep(2);
    } catch (err: any) {
      setError(err.response?.data?.error || "Invalid code");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-8 max-w-3xl mx-auto space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <Shield className="text-green-600" /> Two-Factor Authentication
        </h1>
        <p className="text-slate-500 mt-1">Secure your account with an authenticator app.</p>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8">
        {step === 1 ? (
          <div className="space-y-6">
            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center font-bold">1</div>
              <div>
                <h3 className="font-bold text-slate-800">Download an Authenticator App</h3>
                <p className="text-sm text-slate-500 mt-1">Download and install Google Authenticator, Authy, or Microsoft Authenticator on your phone.</p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center font-bold">2</div>
              <div>
                <h3 className="font-bold text-slate-800">Scan the QR Code</h3>
                <p className="text-sm text-slate-500 mt-1">Open your authenticator app and scan the QR code below.</p>
                {qrCode ? (
                  <img src={qrCode} alt="QR Code" className="mt-4 border border-slate-200 rounded-lg p-2" />
                ) : (
                  <div className="w-48 h-48 bg-slate-100 rounded-lg mt-4 animate-pulse"></div>
                )}
                <p className="text-xs font-mono bg-slate-100 p-2 mt-2 rounded inline-block text-slate-600">{secret}</p>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center font-bold">3</div>
              <div className="w-full">
                <h3 className="font-bold text-slate-800">Verify Code</h3>
                <p className="text-sm text-slate-500 mt-1 mb-3">Enter the 6-digit code generated by the app.</p>
                <div className="flex gap-2 w-full max-w-sm">
                  <input type="text" maxLength={6} value={token} onChange={(e) => setToken(e.target.value.replace(/\D/g, ''))} className="flex-grow px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-center tracking-widest font-mono text-xl" placeholder="000000" />
                  <button onClick={handleVerify} disabled={token.length !== 6 || isLoading} className="bg-slate-900 hover:bg-slate-800 text-white px-6 rounded-xl font-medium disabled:opacity-50">
                    {isLoading ? "..." : "Verify"}
                  </button>
                </div>
                {error && <p className="text-sm text-red-500 mt-2 font-medium">{error}</p>}
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-8">
            <CheckCircle2 className="w-20 h-20 text-green-500 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-slate-900">2FA is Enabled!</h2>
            <p className="text-slate-500 mt-2 max-w-md mx-auto">Your account is now secured with Two-Factor Authentication. You will be required to enter a code each time you sign in.</p>
          </div>
        )}
      </div>
    </div>
  );
};
